### PR TITLE
Subscriber: Sorted lists, batch edit.

### PR DESCRIPTION
**Pull request by attilator**

### CODE REVIEW

**Comment by jarped** [comment]
Could you provide some more detail about what the commit does?

**Comment by attilator** [comment]
Yepp.
Small improvements and some refactoring (not serious):

-         Sorted dataset names in the drop-down list of the dataset combo

-         Sort by column in provider dataset grid

-         Batch edit for data set grid (you can select multiple cells, and update their value)

-         App.config: increased message size limit

These requests was specified by Erlend erlend.klokkervold@kartverket.no<mailto:erlend.klokkervold@kartverket.no>.

If you have any further questions, contact me.


Attila Torjak
Systemutvikler

Kartverket
Hønefoss / IT
I5 Geodata / B 201a
Direct/mob.: +47 47 61 48 30
E-mail: attila.torjak@kartverket.no<mailto:attila.torjak@kartverket.no>

Switchboard: +47 32 11 80 00
www.kartverket.no<http://www.kartverket.no/>

[Logo_kartverket_mail.png]

Fra: Jarle Pedersen [mailto:notifications@github.com]
Sendt: Wednesday, May 23, 2018 14:56
Til: kartverket/geosynkronisering <geosynkronisering@noreply.github.com>
Kopi: Attila Torjak <Attila.Torjak@kartverket.no>; Author <author@noreply.github.com>
Emne: Re: [kartverket/geosynkronisering] Sorted lists, batch edit. (#13)


Could you provide some more detail about what the commit does?

**Comment by jarped** [comment]
I'm afraid merging this now couldmake conflicts when we try to merge the 1.2-branch in. I suggest we merge 1.2 into master first, then try to merge this to master.

**Comment by jarped** [comment]
Closing due to old conflicts and no activity

**Pull request closed without merging**
